x-common:
  panel:
    &panel-environment
    APP_URL: "http://localhost" # kann angepasst werden z.B. http://deine-domain.de
    ADMIN_EMAIL: "USEYOUROWNEMAILHERE@example.com"

    APP_DEBUG: "false"
    APP_ENV: "production"

  mail:
    &mail-environment
    MAIL_DRIVER: "log"
    # MAIL_HOST: ""
    # MAIL_PORT: ""
    # MAIL_FROM: ""
    # MAIL_USERNAME: ""
    # MAIL_PASSWORD: ""
    # MAIL_SCHEME: ""

services:
  panel:
    image: ghcr.io/ivanx77/turbopanel:latest
    build: .
    restart: always
    networks:
      - default
    ports:
      - "80:80"
      - "443:443"
      # - "9000:9000" # wenn du php-fpm direkt brauchst
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - turbopanel-data:/turbopanel-data
      - turbopanel-logs:/var/www/html/storage/logs
    environment:
      <<: [*panel-environment, *mail-environment]
      XDG_DATA_HOME: /turbopanel-data
      # SKIP_CADDY: true # falls kein Caddy benutzt wird

volumes:
  turbopanel-data:
  turbopanel-logs:

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
